### ISSUE TITLE
Build failure due to missing `yylex`

### ISSUE THREAD

**Issue by khinsen** [pantale/ReDynELA#1]
An installation attempt via the supplied instructions fails because of an undefined reference `yylex`:
```
[100%] Linking CXX executable ../../bin/DynELA_solve
ld: /gnu/store/6gvg7cvwbphx3zp4jmy2i4zc9xz7gszq-profile/lib/libfl.so: undefined reference to `yylex'
```

The full build log is attached:
[build.log](https://github.com/pantale/ReDynELA/files/4367993/build.log)

**Comment by pantale** [comment]
Hi,

Pehaps because I'm using the flex-old package instead of the flex one.
Mime is version : 2.5.4a-10ubuntu2

Olivier

**Comment by khinsen** [comment]
Indeed, with flex 2.5 it works for me as well. Could you please add this requirement to the installation instructions?

**Comment by pantale** [comment]
Instructions for the flex 2.5 have been added to the README.md file.

**Comment by khinsen** [comment]
Great, thanks!
